# Generated by Django 4.2.13 on 2024-06-25 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_checkanswer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('pk',), 'verbose_name': 'ответ', 'verbose_name_plural': 'ответы'},
        ),
        migrations.AlterModelOptions(
            name='checkanswer',
            options={'ordering': ('pk',), 'verbose_name': 'проверка ответа', 'verbose_name_plural': 'проверки ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('pk',), 'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
        migrations.AddField(
            model_name='material',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.answer', verbose_name='опросник'),
        ),
    ]
